# -*- coding: utf-8 -*-
"""Practice while Covid+

Automatically generated by Colaboratory.

Original file is located at
    https://colab.corp.google.com/drive/1EuSqzFzV7nhpPlSaSVYZk3RisUdrxDku
"""

print("Hello world")

print('Hello world')

bool(0)

x = 10
y = x + 10
y

